# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.0.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1
  browser-tools: circleci/browser-tools@1.4.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-eb/setup
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: Backend Install
          command: "npm run backend:install"
      - run:
          name: Frontend Install
          command: "npm run frontend:install"
      - run:
          name: Frontend Test
          command: "npm run frontend:test"
      - run:
          name: Backend Build
          command: "npm run backend:build"
      - run:
          name: Frontend Build
          command: "npm run frontend:build"
      - run:
          name: Backend Deploy
          command: "npm run backend:deploy"
      - run:
          name: Frontend Deploy
          command: "npm run frontend:deploy"

